authors:
  zeul:
    name: Zeul Mordasiewicz
    description: Captain
    avatar: https://avatars.githubusercontent.com/u/55005377
    url: https://github.com/zeulewan
  Shivesh:
    name: Shivesh
    description: Future Boomer
    avatar: https://avatars.githubusercontent.com/u/210746825?v=4
    url: https://github.com/Shivesh-MACH
  kolya:
    name: Nikolai
    description: Captain
    avatar: https://avatars.githubusercontent.com/u/145951024
    url: https://github.com/nikolaisydorenko 